# Generated by Django 5.0.7 on 2024-08-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_donation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите chat-id в Телеграм",
                max_length=50,
                null=True,
                verbose_name="Телеграм chat-id ",
            ),
        ),
    ]
